# Generated by Django 3.2 on 2022-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reason',
        ),
        migrations.AddField(
            model_name='contact',
            name='month',
            field=models.CharField(choices=[('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MAR')], default='1', max_length=2),
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
