# Generated by Django 3.2 on 2022-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='inventory',
            new_name='sku',
        ),
    ]
