# Generated by Django 3.2 on 2022-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_inventory_orderlineitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
