# Generated by Django 3.2 on 2022-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='extra_details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
