# Generated by Django 3.2 on 2022-05-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='size',
            new_name='name',
        ),
    ]
