# Generated by Django 3.2 on 2022-05-16 16:22

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_size_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default=products.models.Inventory.create_new_sku_number, editable=False, max_length=10, unique=True),
        ),
    ]
