# Generated by Django 3.2 on 2022-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220516_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, max_length=254, through='products.Inventory', to='products.Color'),
        ),
    ]
