# Generated by Django 3.2 on 2022-06-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220616_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promoted',
        ),
    ]
