# Generated by Django 3.2 on 2022-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
